---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    code_folding: hide
    css: css/theme.css
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
load("./data/instacart.rda")
insta_ez_to_read = instacart %>% 
  select(aisle, everything())

total_aisle_df = insta_ez_to_read %>% 
  group_by(aisle) %>% 
  summarise(total_orders = n(), aisle = first(aisle)) %>%
  arrange(desc(total_orders))

plot_df = total_aisle_df %>% 
  filter(total_orders > 10000)

library(plotly)
plot_df %>% 
  plot_ly(y = ~aisle, x = ~total_orders, type = "bar", mode = "markers", marker = list(color = '#795E4B'))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r, echo=FALSE, warning=FALSE, message=FALSE}
insta_ez_to_read %>% 
  plot_ly(x = ~order_hour_of_day, type = "histogram", mode = "markers", marker = list(color = '#AF8B73'))
```

### Chart C

```{r, echo=FALSE, warning=FALSE, message=FALSE}
cc_df = insta_ez_to_read %>% 
  head(200)

cc_df %>%
  plot_ly(x = ~department_id, y = ~product_id, color = ~aisle,  
          type = "scatter", mode = "markers")
```